source 'https://rubygems.org'

gem 'slack-ruby-client'
gem 'eventmachine'
gem 'faye-websocket'
gem 'byebug'
gem 'mocha'
gem 'webmock'
gem 'vcr'
gem 'simplecov', :require => false, :group => :test
gem 'nokogiri'
gem 'rake'
gem 'sqlite3'
