require 'rake/testtask'

task :default => [:test]

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.test_files = FileList['test/*test.rb', 'test/responses/*test.rb']
  t.verbose = true
  t.warning = false
end
